### PR TITLE
Adding sorting of file list

### PR DESCRIPTION
**Pull request by TheKrush**
This should address #131 (haven't had a chance to test it but it seems pretty simple https://www.geeksforgeeks.org/javascript-array-sort/)

### CODE REVIEW

**Comment by eyal0** [comment]
Want to test it?  You just need to install this:

https://github.com/TheKrush/OctoPrint-PrintTimeGenius/archive/patch-1.zip

You can install that right into OctoPrint from the normal menus.

**Comment by TheKrush** [comment]
> Want to test it? You just need to install this:
> 
> https://github.com/TheKrush/OctoPrint-PrintTimeGenius/archive/patch-1.zip
> 
> You can install that right into OctoPrint from the normal menus.

I'll try it when I get home.

**Comment by TheKrush** [comment]
Do I need to uninstall the main plugin to test this? (sorry first time messing with octoprint plugin coding)

**Comment by eyal0** [comment]
Hmm, I'm not sure!  Just in case, I think that you should.

Uninstalling a plugin doesn't delete the settings so you can just remove one and install another.  It's pretty quick though you'll need to restart OctoPrint when you do it.

**Comment by eyal0** [comment]
This was obviated by #139

**Pull request closed without merging**
